CONTIKI ?= ../../contiki-3.0

all: link_test

CONTIKI_WITH_RIME = 1
DEFINES+=NETSTACK_CONF_RDC=nullrdc_driver
DEFINES+=NETSTACK_CONF_MAC=nullmac_driver
DEFINES+=NETSTACK_CONF_FRAMER=framer_802154
DEFINES+=IEEE802154_CONF_PANID=0xABCD
DEFINES+=RF_CORE_CONF_CHANNEL=26
DEFINES+=CC2420_CONF_CHANNEL=RF_CORE_CONF_CHANNEL
include $(CONTIKI)/Makefile.include
